PAYOUTS:
  UNDERDOG:
    STANDARD:
      "2": 3.0
      "3": 6.0
      "4": 10.0
      "5": 20.0
    FLEX:
      "3": { perfect: 3.0, one_miss: 1.0 }
      "4": { perfect: 6.0, one_miss: 1.5 }
      "5": { perfect: 10.0, one_miss: 2.5 }

FILTERS:
  GLOBAL:
    min_p_final_flex: 0.577
    min_p_final_std:  0.585
    min_roi_flex:     0.03
    min_roi_std:      0.05
    min_odds_low:    -175
    min_odds_high:    160

  RELIABILITY_WEIGHTS:
    NBA:
      pra:   { w_src: 0.55, w_diff: 0.45 }
      pa:    { w_src: 0.60, w_diff: 0.40 }
      ra:    { w_src: 0.55, w_diff: 0.45 }
      pr:    { w_src: 0.55, w_diff: 0.45 }
      ast:   { w_src: 0.60, w_diff: 0.40 }
      reb:   { w_src: 0.58, w_diff: 0.42 }
      "3pm": { w_src: 0.50, w_diff: 0.50 }
    MLB:
      k:            { w_src: 0.65, w_diff: 0.35 }
      outs:         { w_src: 0.60, w_diff: 0.40 }
      hits_allowed: { w_src: 0.55, w_diff: 0.45 }
      walks_allowed:{ w_src: 0.55, w_diff: 0.45 }
      total_bases:  { w_src: 0.52, w_diff: 0.48 }
    NHL:
      sog:   { w_src: 0.62, w_diff: 0.38 }
      saves: { w_src: 0.60, w_diff: 0.40 }
      ast:   { w_src: 0.50, w_diff: 0.50 }
    NFL:
      receptions:      { w_src: 0.62, w_diff: 0.38 }
      rush_attempts:   { w_src: 0.60, w_diff: 0.40 }
      pass_attempts:   { w_src: 0.58, w_diff: 0.42 }
      completions:     { w_src: 0.58, w_diff: 0.42 }
      tackles_assists: { w_src: 0.58, w_diff: 0.42 }

  SIGMA:
    NBA: { points: 7.0, reb: 3.0, ast: 3.2, pa: 6.0, pr: 7.0, ra: 4.8, pra: 8.5, "3pm": 2.0 }
    MLB: { k: 2.0, outs: 2.5, hits_allowed: 1.8, walks_allowed: 1.3, total_bases: 1.2 }
    NHL: { sog: 1.2, saves: 4.0 }
    NFL: { receptions: 1.3, rush_attempts: 3.0, pass_attempts: 5.0, completions: 3.8, tackles_assists: 3.0 }
